git add ex01/print_groups.sh
git add ex02/find_sh.sh
git add ex03/count_files.sh
git add ex04/MAC.sh
git add ex05/\"\\\?\$\*\'KwaMe\'\*\$\?\\\"
git add ex06/skip.sh
git add ex07/r_dwssap.sh
git add ex08/bon.sh
git add ex09/
