git add ex00/ft_putstr.c
git add ex01/ft_putnbr.c
git add ex02/ft_atoi.c
git add ex03/ft_strcpy.c
git add ex04/ft_strncpy.c
git add ex05/ft_strstr.c
git add ex06/ft_strcmp.c
git add ex07/ft_strncmp.c
git add ex08/ft_strupcase.c
git add ex09/ft_strlowcase.c
git add ex10/ft_strcapitalize.c
git add ex11/ft_str_is_alpha.c
git add ex12/ft_str_is_numeric.c
git add ex13/ft_str_is_lowercase.c
git add ex14/ft_str_is_uppercase.c
git add ex15/ft_str_is_printable.c
git add ex16/ft_strcat.c
git add ex17/ft_strncat.c
git add ex18/ft_strlcat.c
git add ex19/ft_strlcpy.c
git add ex20/ft_putnbr_base.c
git add ex/
